### ISSUE TITLE
About PHP 7.1 and Version Above (?)

### ISSUE THREAD

**Issue by salimromadhon** [mecha-cms/genome#44]
With debug option enabled, I tried Mecha on 2 hosting provider (shared).

### Hosting A, B
~~~
Warning: Declaration of Shield::__callStatic($kin, array $lot = Array) should be compatible with Genome::__callStatic(string $kin, array $lot = Array) in .../genome/lot/extend/shield/engine/kernel/shield.php on line 0
~~~

### Hosting A
It results to 500 server error while trying to edit page/file.
~~~
Warning: constant(): Couldn't find constant PLUGIN in .../genome/engine/kernel/extend.php on line 8

Fatal error: Uncaught Error: Call to undefined function mime_content_type() in .../genome/lot/extend/panel/lot/worker/file.php:7 Stack trace: #0 .../genome/lot/extend/panel/_index.php(58): require() #1 .../genome/lot/extend/panel/index.php(51): require('/home/kreasinu/...') #2 .../genome/engine/fire.php(170): require('/home/kreasinu/...') #3 .../genome/engine/fire.php(171): {closure}() #4 .../genome/index.php(50): require('/home/kreasinu/...') #5 {main} thrown in .../genome/lot/extend/panel/lot/worker/file.php on line 7
~~~

### Hosting B
Can login, but can't visit panel (404 Not Found).

***

On my localhost, running PHP 7.2 I didn't get any PHP error but this warning everywhere.
~~~
Warning: constant(): Couldn't find constant PLUGIN in .../genome/engine/kernel/extend.php on line 8
~~~

**Comment by taufik-nurrohman** [comment]
`PLUGIN` constant is defined in `.\lot\extend\plugin\index.php` if it&rsquo;s not defined then that means the file above failed to load, or it means that I have declared `Plugin::state()` before the above file is loaded.
